apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ci-rabbitmq
  namespace: default
spec:
  endpoints:
    - interval: 15s
      port: prometheus
      scheme: http
      scrapeTimeout: 14s
    - interval: 15s
      port: prometheus-tls
      scheme: https
      scrapeTimeout: 14s
      tlsConfig:
        insecureSkipVerify: true
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app.kubernetes.io/component: rabbitmq
