apiVersion: batch/v1
kind: Job
metadata: 
  name: pluto
spec:
   template:
    spec:
      containers:
        - command:
          - /bin/sh
          - -c
          - sleep 5m
          image: 'alpine:latest'
          imagePullPolicy: Always
          name: reset-counters-rossum-cron-rentpath-cronjob
      restartPolicy: OnFailure