---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: rabbitmq-system
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
  destination:
    namespace: rabbitmq-system
    server: 'https://kubernetes.default.svc'
  project: default
  revisionHistoryLimit: 2
  source:
    chart: rabbitmq-cluster-operator
    helm:
      releaseName: rabbitmq
      values: |+
        fullnameOverride: "rabbitmq-cluster-operator"
        clusterOperator:
          resources:
            limits:
              cpu: 200m
              memory: 500Mi
            requests:
              cpu: 200m
              memory: 500Mi
          rabbitmqImage:
            tag: 3.8.9-1.el7
          metrics:
            enabled: true
            serviceMonitor:
              enabled: true
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 2.6.1
