apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: rabbitmq-system
  namespace: argocd
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: nonprod/common/system/rabbitmq-system/rabbitmq-old
    repoURL: 'https://github.com/JDKnobloch/test-delete.git'
    targetRevision: HEAD
    directory:
      recurse: true
  project: default
  revisionHistoryLimit: 1
