apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: rabbitmq-cluster-operator
  namespace: rabbitmq-system
spec:
  namespaceSelector:
    any: true
  podMetricsEndpoints:
    - targetPort: 9782
      path: /metrics
  selector:
    matchLabels:
      app.kubernetes.io/component: rabbitmq-operator
